# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d0b98afebade03e951b1a0bf7977acd"
name = "app-remixjs"
handle = "app-remixjs"
application_url = "https://scholar-contrary-outreach-diamonds.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://scholar-contrary-outreach-diamonds.trycloudflare.com/auth/callback", "https://scholar-contrary-outreach-diamonds.trycloudflare.com/auth/shopify/callback", "https://scholar-contrary-outreach-diamonds.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
